### ISSUE TITLE
do you still have your anti ip logger

### ISSUE THREAD

**Issue by 1923812371283127398123712893126793** [broflovsk/consultar-empresa-api#1]
do you have your anti ip logger script? (roblox lua) i cant find it anywhere

**Comment by broflovsk** [comment]
> do you have your anti ip logger script? (roblox lua) i cant find it anywhere

yea

**Comment by broflovsk** [comment]
https://github.com/broflovsk/Roblox-IP-Spoofer

**Comment by broflovsk** [comment]
> do you have your anti ip logger script? (roblox lua) i cant find it anywhere

https://github.com/broflovsk/Roblox-IP-Spoofer
